### ISSUE TITLE
In Readme.md change "git submodule ini" to "git submodule init"?

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-docker#2]
@wsalesky Reading here: https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by wsalesky** [comment]
@nathangibson Don't use this, use: https://hub.docker.com/repository/docker/srophe/syriaca.org

I need to depreciate this repository.

**Comment by nathangibson** [comment]
When you say you need to deprecate this repository ... which repository (if any) should I fork in order to use the Dockerfile and existing setup you've created for usaybia?

**Comment by wsalesky** [comment]
Fixed. You can use this now. Just remove the srophe.xars and add the Usaybia. I am working on a version that also hooks up a triplestore as there are issues with the eXist-db SPARQL module. Will add a docker-compose file when I have it running smoothly.
